services:
  stratify-s3:
    build:
      context: .
      dockerfile: Dockerfile
    image: stratify-s3:latest
    container_name: stratify-s3
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
    volumes:
      # ストレージボリューム
      - primary-storage:/storage/primary
      - secondary-storage:/storage/secondary
      - archive-storage:/storage/archive
      # 設定ファイルのオーバーライド（オプション）
      #- ./src/appsettings.Production.json:/app/appsettings.Production.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  primary-storage:
    driver: local
  secondary-storage:
    driver: local
  archive-storage:
    driver: local
